export type Node={id:string;name:string;subtitle:string;tag:string;kind:'client'|'service'|'data'|'external';icon:string;x:number;y:number;description:string;responsibilities:string[];inputs:string[];outputs:string[];fields?:string[]};
export type Edge={from:string;to:string;label?:string;side?:boolean;detour?:boolean};
export type Diagram={id:string;name:string;subtitle:string;width:number;height:number;nodes:Node[];edges:Edge[];bands?:{y:number;label:string;hint:string}[]};
const n=(id:string,name:string,subtitle:string,tag:string,kind:Node['kind'],icon:string,x:number,y:number,description:string,responsibilities:string[],inputs:string[],outputs:string[],fields?:string[]):Node=>({id,name,subtitle,tag,kind,icon,x,y,description,responsibilities,inputs,outputs,fields});
export const diagrams:Diagram[]=[{
id:'system',name:'Sistem mimarisi',subtitle:'Mobil uygulama, servisler ve kalıcı verinin ilişkisi.',width:1030,height:810,
bands:[{y:30,label:'01 / MOBİL DENEYİM',hint:'Kullanıcının cihazı'},{y:295,label:'02 / UYGULAMA SERVİSLERİ',hint:'Kimlik, kurallar ve iletişim'},{y:560,label:'03 / KALICI VERİ',hint:'Yetkilendirilmiş depolama'}],
nodes:[
n('mobile','Patika mobil','React Native · Expo','iOS + Android','client','mobile',395,90,'Hayvanseverin parkları keşfettiği, besleme geçmişini gördüğü ve mama/su kaydı oluşturduğu mobil uygulama.',['Harita ve besleme noktası ekranları','Fotoğraf, yaklaşık gramaj ve su kaydı','Yükleme, hata ve bağlantı durumları'],['Parklar ve besleme geçmişi','Kullanıcının konum izni ve form bilgileri'],['Yetkilendirilmiş kayıt istekleri','Fotoğraf yükleme isteği']),
n('offline','Çevrimdışı kayıt','Cihazda yerel kuyruk','Tekrar gönderme','client','offline',75,90,'İnternet yokken tamamlanan formu cihazda saklar. Bağlantı geldiğinde aynı işlem kimliğiyle tekrar gönderir.',['Bekleyen kayıt ve fotoğraf referansı','Gönderildi / bekliyor / hata durumu','Tek işlem için tek benzersiz kimlik'],['Gönderilemeyen besleme kaydı'],['Bağlantı geldiğinde yeniden gönderim']),
n('maps','Harita sağlayıcısı','Harita görselleri ve konum','Sağlayıcı seçilecek','external','map',715,90,'Harita zeminini sağlar. Bu hizmet ile uygulamanın park ve besleme kayıtları ayrı veri kaynaklarıdır.',['Harita çizimi ve gezinme','Kullanım lisansı ve kota yönetimi','Cihaz uyumunu doğrulama'],['Görünen coğrafi bölge'],['Harita zemini']),
n('auth','Kimlik & erişim','Supabase Auth + RLS','Yetkilendirme','service','shield',75,355,'Kullanıcı kimliğini doğrular. Veritabanı kuralları hangi kayıtları okuyup değiştirebileceğini belirler.',['Oturum doğrulama','Kullanıcı ve moderatör yetkileri','Kayıt sahipliğini veritabanında denetleme'],['Giriş isteği / oturum bilgisi'],['Doğrulanmış kimlik','Veri erişim kararı']),
n('api','Besleme servisi','Supabase API · RPC / Functions','İş kuralları','service','server',395,355,'Besleme ve konum sorgularını doğrular. Aynı işlemin iki kez kaydedilmesini önler; geçmişi olay zamanına göre sunar.',['Girdi ve kullanıcı doğrulama','İşlem kimliğiyle mükerrer kayıt önleme','Besleme olayı ile gözlemi ayrı tutma','Görünen harita bölgesini sorgulama'],['Konum sorgusu','Mama/su veya gözlem kaydı'],['Doğrulanmış kayıt sonucu','Nokta geçmişi ve güncellik']),
n('push','Bildirim servisi','Expo Push → APNs / FCM','Tercihe bağlı','service','bell',715,355,'Takip edilen noktalardaki anlamlı değişiklikleri kullanıcı tercihine göre iletir. Bildirim teslimatı besleme kaydından bağımsızdır.',['Nokta takibi ve kullanıcı tercihleri','Tekrarlayan bildirimleri sınırlandırma','Geçersiz cihaz tokenlarını temizleme'],['Nokta güncellemesi','Bildirim tercihleri'],['Mobil cihaza bildirim']),
n('parks','Park veri kaynağı','OpenStreetMap · açık veri','Kapsam doğrulanacak','external','tree',75,620,'Park adları ve sınırları için başlangıç kaynağı. Eksik ve tekrarlanan parklar kontrol edilerek uygulamanın veritabanına alınır.',['Kaynak ve güncelleme tarihini saklama','Lisans ve kaynak gösterimi','Park kapsamı ve mükerrer kayıt kontrolü'],['Lisansı uygun park veri setleri'],['Doğrulanmış park kayıtları']),
n('db','PostgreSQL + PostGIS','İlişkisel ve coğrafi veri','Kalıcı kayıt','data','database',395,620,'Parkları, noktaları, besleme olaylarını ve gözlemleri ilişkili biçimde saklar. Konum sorgularını coğrafi indekslerle yürütür.',['Park → nokta → olay ilişkileri','Olay ve kayıt zamanını ayrı saklama','İşlem kimliğine benzersizlik kuralı','Erişim politikaları ve yedekler'],['Doğrulanmış olay ve gözlemler','Park veri aktarımı'],['Yakın noktalar','Besleme ve gözlem geçmişi']),
n('storage','Fotoğraf depolama','Supabase Storage','Kontrollü erişim','data','image',715,620,'Fotoğraf dosyalarını saklar. Veritabanında dosya referansı bulunur; erişim kullanıcı ve kayıt kurallarıyla sınırlandırılır.',['Dosya türü ve boyut sınırı','Kullanıcıya ve kayda bağlı erişim','Gereksiz fotoğraf meta verisini temizleme'],['İzinli fotoğraf yüklemesi'],['Dosya referansı','Yetkili görüntüleme bağlantısı'])
],edges:[{from:'offline',to:'mobile',label:'bekleyen kayıt',side:true},{from:'mobile',to:'maps',label:'harita',side:true},{from:'mobile',to:'api',label:'HTTPS / JSON'},{from:'auth',to:'api',label:'kimlik',side:true},{from:'api',to:'push',label:'güncelleme',side:true},{from:'api',to:'db',label:'oku / kaydet'},{from:'api',to:'storage',label:'fotoğraf'},{from:'parks',to:'db',label:'veri aktarımı',side:true}]},
{id:'data',name:'Veri modeli',subtitle:'Bir park, birden fazla nokta. Her olayın kendi kaydı.',width:1030,height:810,nodes:[
n('user','Kullanıcı','users','Kimlik','client','user',75,75,'Besleme ve gözlem kayıtlarını oluşturan gönüllü. Olaylar kullanıcı kimliğiyle ilişkilendirilir.',['Kayıt sahipliği','Bildirim tercihleri'],['Doğrulanmış oturum'],['Kullanıcı kimliği'],['id · uuid · PK','display_name · text','created_at · timestamp']),
n('park','Park','parks','Coğrafi alan','external','tree',715,75,'Park adı, coğrafi sınırı ve veri kaynağı. Tek park içinde birden fazla besleme noktası bulunabilir.',['Park sınırı ve kaynak bilgisi'],['Doğrulanmış park verisi'],['Park içindeki noktalar'],['id · uuid · PK','name · text','boundary · geometry','source_id · text']),
n('point','Besleme noktası','feeding_points','Park içinde konum','service','map',395,300,'Hayvanların beslendiği belirli yer. Besleme olayları ile durum gözlemleri ayrı kayıtlardır.',['Park ile ilişki','Nokta bazında geçmiş'],['Park kimliği','Nokta konumu'],['Besleme ve gözlem bağlantıları'],['id · uuid · PK','park_id · uuid · FK','location · geography','name · text']),
n('feeding','Besleme olayı','feeding_events','Ne bırakıldı?','data','database',75,565,'Belirli zamanda bırakılan mama veya suyun kaydı. Bırakılan miktar, şu anda kalan miktarı göstermez.',['Mama türü ve yaklaşık miktar','Su bırakma bilgisi','Tekrar gönderimde aynı olayı koruma'],['Nokta ve kullanıcı kimliği','Miktar ve olay zamanı'],['Besleme geçmişi'],['id · uuid · PK','point_id, user_id · FK','operation_id · uuid · UNIQUE','food_type · text','estimated_grams · integer','water_added · boolean','occurred_at · timestamp','received_at · timestamp']),
n('observation','Durum gözlemi','observations','Ne görüldü?','data','eye',395,565,'Noktada görülen mama/su durumu. Mama bırakmadan da gözlem yapılabilir; eski bilgi güncel gibi sunulmaz.',['Mama ve su durumunu ayrı kaydetme','Gözlem zamanı ve güncellik'],['Nokta ve kullanıcı kimliği','Kap durumu'],['Zaman damgalı gözlem'],['id · uuid · PK','point_id, user_id · FK','food_status · enum','water_status · enum','observed_at · timestamp']),
n('photo','Fotoğraf','photos','Dosya referansı','data','image',715,565,'Besleme veya gözleme bağlı dosya referansı. Fotoğraf tek başına gramajı veya olayın doğruluğunu kanıtlamaz.',['Dosyayla olay arasında ilişki','Yetkilendirilmiş erişim'],['Besleme veya gözlem kimliği'],['Dosya referansı'],['id · uuid · PK','feeding_event_id · uuid · FK','observation_id · uuid · FK','storage_path · text','created_at · timestamp','CHECK: yalnızca bir olay bağlantısı'])
],edges:[{from:'user',to:'feeding',label:'1 kullanıcı → N olay'},{from:'park',to:'point',label:'1 park → N nokta'},{from:'point',to:'feeding',label:'1 → N'},{from:'point',to:'observation',label:'1 → N'},{from:'feeding',to:'photo',label:'olay fotoğrafı',detour:true},{from:'observation',to:'photo',label:'gözlem fotoğrafı',side:true}]},
{id:'flow',name:'Besleme akışı',subtitle:'Nokta seçiminden ortak geçmişe, kayıt nasıl ilerler?',width:1030,height:860,nodes:[
n('select','Noktayı seç','Harita → nokta detayı','01','client','map',75,70,'Kullanıcı park içindeki besleme noktasını seçer ve önceki kayıtların zamanını görür.',['Doğru noktayı belirleme','Son kaydın güncelliğini gösterme'],['Harita veya park seçimi'],['Besleme noktası kimliği']),
n('form','Beslemeyi kaydet','Fotoğraf · gramaj · su','02','client','image',395,70,'Fotoğraf, mama türü, yaklaşık miktar ve su bilgisi alınır. Olay zamanı ayrıca saklanır.',['Form doğrulama','Benzersiz işlem kimliği oluşturma'],['Nokta kimliği','Kullanıcının beyanı'],['Gönderilmeye hazır olay']),
n('connection','Bağlantıyı kontrol et','Çevrimiçi / çevrimdışı','03','service','offline',715,70,'İnternet varsa gönderilir. Yoksa kayıt cihazda bekler; bağlantı gelince aynı işlem kimliğiyle yeniden gönderilir.',['Bağlantı yoksa kaydı koruma','Bekleyen durumu görünür tutma'],['Hazır kayıt'],['İstek veya yerel bekleme kuyruğu']),
n('validate','Kimliği ve veriyi doğrula','Sunucu tarafında kontrol','04','service','shield',715,355,'Sunucu oturumu, nokta kimliğini ve alanları doğrular. Hatalı istek reddedilir; cihazdaki taslak korunur.',['Kullanıcı ve girdi doğrulama','Erişim kurallarını uygulama'],['Oturum + kayıt isteği'],['Geçerli istek veya hata']),
n('deduplicate','Tekrarı engelle','operation_id benzersizliği','05','service','copy',395,355,'Aynı işlem yeniden ulaştıysa yeni bir besleme oluşturulmaz. Mevcut kayıt sonucu döndürülür.',['İşlem kimliğini benzersiz tutma','Tekrarda mevcut sonucu döndürme'],['Doğrulanmış olay'],['Yeni veya mevcut kayıt sonucu']),
n('persist','Olayı kalıcı kaydet','Veritabanı + dosya referansı','06','data','database',75,355,'Besleme olayı ve fotoğraf referansı saklanır. Fotoğraf yüklemesi ile olay kaydının başarısızlıkları ayrı ele alınır.',['Olayı atomik kaydetme','Olay ve alınma zamanını ayırma','Başarısız yüklemeyi tekrar deneme'],['Geçerli kayıt'],['Kalıcı kayıt kimliği']),
n('result','Sonucu göster','Kaydedildi / bekliyor / hata','07','client','check',75,640,'Sunucu onayından sonra kaydedildi durumu gösterilir. Bekleyen işlem tamamlanmış gibi sunulmaz.',['Doğru işlem durumu','Tekrar deneme ve geçmiş bağlantısı'],['Sunucu cevabı'],['Açık kayıt sonucu']),
n('history','Nokta geçmişini yenile','Zaman damgalı kayıtlar','08','data','history',395,640,'Olay noktanın geçmişine eklenir. Sonradan ulaşan eski olay, güncel gözlemi geriye götürmez.',['Olay zamanına göre geçmiş','Son kayıt ile mevcut durumu ayırma'],['Yeni olay'],['Güncel nokta geçmişi']),
n('notify','Takipçileri bilgilendir','Bildirim tercihine göre','09','external','bell',715,640,'Anlamlı güncelleme takip eden ve bildirim isteyen kullanıcılara gönderilir. Bildirim hatası besleme kaydını geri almaz.',['Tercihe göre bildirim','Tekrarlayan bildirimleri sınırlandırma'],['Nokta güncellemesi'],['İsteğe bağlı bildirim'])
],edges:[{from:'select',to:'form',side:true},{from:'form',to:'connection',side:true},{from:'connection',to:'validate',label:'hazır olduğunda'},{from:'validate',to:'deduplicate',side:true},{from:'deduplicate',to:'persist',side:true},{from:'persist',to:'result',label:'sunucu onayı'},{from:'result',to:'history',side:true},{from:'history',to:'notify',side:true}]}
];
