const fs = require('node:fs');
const path = require('node:path');
const { buildSync } = require('esbuild');
const root = path.resolve(__dirname, '..');
const options = {
  bundle: true,
  write: false,
  minify: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  legalComments: 'inline',
};
const worker = buildSync({
  ...options,
  entryPoints: [require.resolve('maplibre-gl/dist/maplibre-gl-worker.mjs')],
}).outputFiles[0].text;
const runtime = buildSync({
  ...options,
  entryPoints: [path.join(root, 'src/components/map-runtime.ts')],
  globalName: 'PatikaMap',
  define: { 'import.meta.url': 'document.baseURI' },
}).outputFiles[0].text;
const css =
  fs.readFileSync(require.resolve('maplibre-gl/dist/maplibre-gl.css'), 'utf8') +
  '\n' +
  fs.readFileSync(path.join(root, 'src/components/map-theme.css'), 'utf8');
fs.writeFileSync(
  path.join(root, 'src/components/map-bundle.ts'),
  '// Generated by scripts/build-map.cjs. MapLibre BSD-3-Clause; Supercluster ISC.\n' +
    Object.entries({ mapRuntime: runtime, mapWorker: worker, mapCss: css })
      .map(([key, value]) => `export const ${key} = ${JSON.stringify(value)};`)
      .join('\n') +
    '\n',
);
console.log('Shared web/native map bundle generated.');
