'use client';
import { useEffect,useRef,useState } from 'react';
import { ArrowDownLeft,ArrowUpRight,Bell,Check,ChevronRight,CircleHelp,CloudOff,Copy,Database,Eye,Github,History,Image as ImageIcon,Layers,Map,Maximize2,Minus,MousePointer2,Network,Plus,RotateCcw,Route,Server,ShieldCheck,Smartphone,Sprout,TreePine,User,X } from 'lucide-react';
import { diagrams,type Node } from '@/lib/architecture';
const icons:Record<string,typeof Smartphone>={mobile:Smartphone,offline:CloudOff,map:Map,shield:ShieldCheck,server:Server,bell:Bell,tree:TreePine,database:Database,image:ImageIcon,user:User,eye:Eye,copy:Copy,check:Check,history:History};
const baseKinds={client:{name:'Mobil uygulama',color:'#5276dc'},service:{name:'Uygulama servisi',color:'#9271c9'},data:{name:'Kalıcı veri',color:'#358879'},external:{name:'Harici hizmet',color:'#b68a47'}};
const W=240,H=135;
export function Architecture(){
 const [tab,setTab]=useState('system'),[selected,setSelected]=useState('mobile'),[zoom,setZoom]=useState(1),[size,setSize]=useState(1000),[inspector,setInspector]=useState(true),[fullscreenError,setFullscreenError]=useState('');
 const viewport=useRef<HTMLDivElement>(null);const graph=diagrams.find(d=>d.id===tab)!;const current=graph.nodes.find(n=>n.id===selected);const scale=Math.max(.58,Math.min(1,size/graph.width))*zoom;
 useEffect(()=>{const el=viewport.current;if(!el)return;const ro=new ResizeObserver(([e])=>setSize(e.contentRect.width));ro.observe(el);return()=>ro.disconnect();},[]);
 const kinds=tab==='data'?{client:{...baseKinds.client,name:'Kimlik'},service:{...baseKinds.service,name:'Besleme noktası'},data:{...baseKinds.data,name:'Olay ve medya'},external:{...baseKinds.external,name:'Coğrafi alan'}}:baseKinds; const connected=new Set(graph.edges.filter(e=>e.from===selected||e.to===selected).flatMap(e=>[e.from,e.to]));
 function switchTab(id:string){viewport.current?.scrollTo({top:0,left:0});setTab(id);setSelected(id==='system'?'mobile':id==='data'?'point':'select');setZoom(1);}
 function choose(n:Node){setSelected(n.id);setInspector(true);}
 async function fullscreen(){try{if(!document.fullscreenElement)await viewport.current?.requestFullscreen();else await document.exitFullscreen();}catch{setFullscreenError('Bu tarayıcıda tam ekran açılamadı. Bileşen detayını kapatarak diyagramı genişletebilirsiniz.');}}
 return <div className="atlas"><header className="atlas-header"><a href="/" className="atlas-brand"><span><Sprout size={24}/></span>patika<span className="brand-divider"/><small>Mimari atlası</small></a><div className="atlas-header-right"><span className="draft-label"><span/> Önerilen mimari</span><a href="https://github.com/aRdaOnur/patika-project" target="_blank" rel="noreferrer"><Github size={17}/><span>Özel depo</span><ArrowUpRight size={14}/></a></div></header>
 <section className="atlas-title"><div><span className="atlas-eyebrow">PATİKA MOBİL UYGULAMASI</span><h1>Projenin büyük resmi.</h1><p>Bileşenler, veri ilişkileri ve besleme kaydının izlediği yol.</p></div><div className="platform-badges"><span><Smartphone size={15}/> React Native + Expo</span><span><Database size={15}/> PostgreSQL + PostGIS</span></div></section>
 <div className="atlas-workspace"><div className="atlas-toolbar"><nav aria-label="Mimari görünümleri">{diagrams.map((d,i)=>{const Icon=[Network,Database,Route][i];return <button key={d.id} aria-pressed={tab===d.id} onClick={()=>switchTab(d.id)}><Icon size={17}/>{d.name}</button>;})}</nav><button className={`inspector-toggle ${inspector?'is-active':''}`} onClick={()=>setInspector(!inspector)} aria-pressed={inspector} aria-label="Bileşen detayını göster veya gizle"><Layers size={17}/><span>Bileşen detayı</span></button></div>
 <div className={`atlas-body ${inspector?'with-inspector':''}`}><div className="graph-area"><div className="graph-caption"><span><span className="graph-status"/>{graph.name}</span><span>{graph.nodes.length} bileşen <span className="caption-separator">/</span> {graph.edges.length} bağlantı</span></div><div className="graph-viewport" ref={viewport} tabIndex={0} aria-label="Mimari diyagramı"><div className="graph-sizer" style={{width:graph.width*scale,height:graph.height*scale,minWidth:'100%'}}><div className="graph-stage" style={{width:graph.width,height:graph.height,transform:`scale(${scale})`}}>
 {(graph.bands??[]).map(b=><div key={b.y} className="layer-label" style={{top:b.y}}><strong>{b.label}</strong><span>{b.hint}</span><i/></div>)}
 <svg className="graph-edges" width={graph.width} height={graph.height} aria-hidden="true"><defs><marker id="arrow-muted" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#aab7c5"/></marker><marker id="arrow-active" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#6886c7"/></marker></defs>{graph.edges.map((e,i)=>{const a=graph.nodes.find(n=>n.id===e.from)!,b=graph.nodes.find(n=>n.id===e.to)!;const active=e.from===selected||e.to===selected;let ax:number,ay:number,bx:number,by:number,path:string,lx:number,ly:number;
 if(e.detour){ax=a.x+W/2;ay=a.y+H;bx=b.x+W/2;by=b.y+H;const mid=ay+65;path=`M${ax},${ay} L${ax},${mid} L${bx},${mid} L${bx},${by}`;lx=(ax+bx)/2;ly=mid;}
 else if(e.side){const right=b.x>a.x;ax=a.x+(right?W:0);ay=a.y+H/2;bx=b.x+(right?0:W);by=b.y+H/2;const mid=(ax+bx)/2;path=`M${ax},${ay} C${mid},${ay} ${mid},${by} ${bx},${by}`;lx=(ax+bx)/2;ly=(ay+by)/2;}
 else{ax=a.x+W/2;ay=a.y+H;bx=b.x+W/2;by=b.y;const mid=(ay+by)/2;path=`M${ax},${ay} C${ax},${mid} ${bx},${mid} ${bx},${by}`;lx=(ax+bx)/2;ly=(ay+by)/2;}
 const labelLines=e.side&&e.label?e.label.split(' '):[e.label??''];const labelY=e.side?ly-20-(labelLines.length-1)*14:ly+4;const labelWidth=e.side?76:134; return <g key={`${tab}-${i}`} className={!active?'edge-dim':''}><path d={path} fill="none" stroke={active?'#6886c7':'#b1bdca'} strokeWidth={active?2.2:1.5} markerEnd={`url(#arrow-${active?'active':'muted'})`}/>{e.label?<g><rect x={lx-labelWidth/2} y={labelY-12} width={labelWidth} height={labelLines.length*14+4} fill="#fafbfd" rx="5"/><text textAnchor="middle" fill={active?'#6480b6':'#8a97a8'} fontSize="12" fontFamily="Arial,sans-serif">{labelLines.map((line,index)=><tspan key={index} x={lx} y={labelY+index*14}>{line}</tspan>)}</text></g>:null}</g>;})}</svg>
 {graph.nodes.map(n=>{const Icon=icons[n.icon]??Server;const k=kinds[n.kind];return <button key={`${tab}-${n.id}`} className={`graph-node ${n.kind} ${selected===n.id?'selected':''} ${selected!==n.id&&!connected.has(n.id)?'node-muted':''}`} style={{left:n.x,top:n.y,width:W,height:H,'--node-color':k.color} as React.CSSProperties} onClick={()=>choose(n)} aria-pressed={selected===n.id}><span className="node-top"><span className="node-icon"><Icon size={21}/></span><span className="node-tag">{n.tag}</span></span><strong>{n.name}</strong><span className="node-subtitle">{n.subtitle}</span><span className="node-port top"/><span className="node-port bottom"/></button>;})}
 </div></div></div><div className="canvas-controls"><span className="canvas-hint"><MousePointer2 size={14}/> Ayrıntıları görmek için bir bileşen seçin</span><div className="zoom-controls"><button aria-label="Küçült" disabled={zoom<=.6} onClick={()=>setZoom(z=>Math.max(.6,z-.15))}><Minus size={16}/></button><span>%{Math.round(zoom*100)}</span><button aria-label="Büyüt" disabled={zoom>=2} onClick={()=>setZoom(z=>Math.min(2,z+.15))}><Plus size={16}/></button><i/><button aria-label="Ekrana sığdır" onClick={()=>setZoom(1)}><RotateCcw size={15}/></button><button aria-label="Diyagramı tam ekran aç" onClick={()=>void fullscreen()}><Maximize2 size={16}/></button></div></div>{fullscreenError?<p className="fullscreen-error" role="status">{fullscreenError}</p>:null}<div className="graph-legend">{Object.entries(kinds).map(([id,k])=><span key={id}><i style={{background:k.color}}/>{k.name}</span>)}<span className="legend-note">Oklar veri veya kontrol ilişkisini gösterir.</span></div></div>
 {inspector?<aside className="node-inspector"><div className="inspector-heading"><span>BİLEŞEN DETAYI</span><button aria-label="Detayı kapat" onClick={()=>setInspector(false)}><X size={17}/></button></div>{current?<><div className={`detail-icon ${current.kind}`}>{(()=>{const Icon=icons[current.icon]??Server;return <Icon size={27}/>;})()}</div><span className="detail-kind">{kinds[current.kind].name}</span><h2>{current.name}</h2><p className="detail-tech">{current.subtitle}</p><p className="detail-description">{current.description}</p><section className="detail-section"><h3>NE YAPAR?</h3><ul>{current.responsibilities.map(r=><li key={r}><Check size={14}/><span>{r}</span></li>)}</ul></section>{current.fields?<section className="detail-section"><h3>ÖNERİLEN ALANLAR</h3><div className="field-list">{current.fields.map(f=><code key={f}>{f}</code>)}</div></section>:null}<section className="detail-section"><h3>GİRDİLER</h3>{current.inputs.map(t=><div className="io-item" key={t}><ArrowDownLeft size={14}/>{t}</div>)}</section><section className="detail-section"><h3>ÇIKTILAR</h3>{current.outputs.map(t=><div className="io-item" key={t}><ArrowUpRight size={14}/>{t}</div>)}</section><section className="detail-section"><h3>BAĞLANTILI BİLEŞENLER</h3>{graph.nodes.filter(n=>n.id!==current.id&&connected.has(n.id)).map(n=><button className="related-node" key={n.id} onClick={()=>choose(n)}><span style={{background:kinds[n.kind].color}}/>{n.name}<ChevronRight size={14}/></button>)}</section></>:null}</aside>:null}</div></div>
 <footer className="atlas-footer"><span><CircleHelp size={15}/> Önerilen tasarım. Mobil uygulamanın uygulanmış durumunu göstermez.</span><span>Patika <span className="footer-dot">·</span> Mimari v0.1</span></footer></div>;
}
